#!/bin/zsh
#set -o xtrace
targetSizeKilobytes=8192
fileInput=$1
ext="${fileInput##*.}"; 
fileOutput="${fileInput}.cropped.${ext}"
ffmpeg -i $1 -vf "crop=1080:1080" $fileOutput
fileInput="${fileInput}.cropped.${ext}"
fileOutput="${fileInput}.cropped.${ext}"
fileOutput="${fileInput}.shrunk.${ext}"
durationSeconds=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 $fileInput)
bitrate=160
#bitrate=$(($targetSizeKilobytes / $durationSeconds))
beforeSizeBytes=$(stat --printf="%s" $fileInput)
echo "Shrinking ${fileInput} to ${targetSizeKilobytes}KB. Bitrate: ${bitrate}k"
ffmpeg \
	-y \
	-hide_banner \
	-loglevel error \
	-i "$fileInput" \
	-b ${bitrate}k \
	-cpu-used 6 \
	-c:a copy \
	$fileOutput
afterSizeBytes=$(stat --printf="%s" $fileOutput)
shrinkPercentage=$(($beforeSizeBytes / $afterSizeBytes))
echo "Rebuilt file as ${fileOutput}, shrank to ${shrinkPercentage}% of original size"

ffmpeg -t 8 -i $fileOutput -filter_complex "[0:v] fps=24,scale=-1:360,mpdecimate,split [a][b];[a] palettegen=max_colors=64 [p];[b][p] paletteuse=dither=bayer:bayer_scale=5" $fileOutput.gif
#ffmpeg -t 8 -i $fileOutput $fileOutput.gif


